initialMarketData =
    [
        {
            "State": "Maharashtra",
            "District": "Raigad",
            "Market": "Panvel",
            "Commodity": "Coriander(Leaves)",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "10/11/2006",
            "Min_Price": "300",
            "Max_Price": "400",
            "Modal_Price": "350",
            "Commodity_Code": "43"
        },
        {
            "State": "Maharashtra",
            "District": "Chandrapur",
            "Market": "Chandrapur",
            "Commodity": "Mousambi(Sweet Lime)",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "02/02/2006",
            "Min_Price": "900",
            "Max_Price": "1200",
            "Modal_Price": "1100",
            "Commodity_Code": "77"
        },
        {
            "State": "Maharashtra",
            "District": "Chandrapur",
            "Market": "Chandrapur",
            "Commodity": "Pumpkin",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "01/02/2006",
            "Min_Price": "200",
            "Max_Price": "400",
            "Modal_Price": "300",
            "Commodity_Code": "84"
        },
        {
            "State": "Maharashtra",
            "District": "Ahmednagar",
            "Market": "Sangamner",
            "Commodity": "Cowpea (Lobia/Karamani)",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "15/09/2006",
            "Min_Price": "1226",
            "Max_Price": "1235",
            "Modal_Price": "1230",
            "Commodity_Code": "92"
        },
        {
            "State": "Maharashtra",
            "District": "Mumbai",
            "Market": "Mumbai",
            "Commodity": "Mataki",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "05/08/2006",
            "Min_Price": "3100",
            "Max_Price": "3125",
            "Modal_Price": "3112",
            "Commodity_Code": "93"
        },
        {
            "State": "Maharashtra",
            "District": "Kolhapur",
            "Market": "Kolhapur",
            "Commodity": "Beans",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "02/08/2006",
            "Min_Price": "800",
            "Max_Price": "1100",
            "Modal_Price": "950",
            "Commodity_Code": "94"
        },
        {
            "State": "Maharashtra",
            "District": "Pune",
            "Market": "Pune",
            "Commodity": "Banana - Green",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "07/05/2006",
            "Min_Price": "400",
            "Max_Price": "500",
            "Modal_Price": "450",
            "Commodity_Code": "90"
        },
        {
            "State": "Maharashtra",
            "District": "Raigad",
            "Market": "Pen",
            "Commodity": "Rice",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "19/05/2006",
            "Min_Price": "1100",
            "Max_Price": "1450",
            "Modal_Price": "1250",
            "Commodity_Code": "3"
        },
        {
            "State": "Maharashtra",
            "District": "Mumbai",
            "Market": "Mumbai",
            "Commodity": "Cardamoms",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "22/03/2006",
            "Min_Price": "25000",
            "Max_Price": "48000",
            "Modal_Price": "36500",
            "Commodity_Code": "40"
        },
        {
            "State": "Maharashtra",
            "District": "Ahmednagar",
            "Market": "Ahmednagar",
            "Commodity": "Gur(Jaggery)",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "20/01/2006",
            "Min_Price": "1411",
            "Max_Price": "1451",
            "Modal_Price": "1431",
            "Commodity_Code": "74"
        },
        {
            "State": "Maharashtra",
            "District": "Dhule",
            "Market": "Shirpur",
            "Commodity": "Black Gram (Urd Beans)(Whole)",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "10/11/2006",
            "Min_Price": "3000",
            "Max_Price": "3325",
            "Modal_Price": "3051",
            "Commodity_Code": "8"
        },
        {
            "State": "Maharashtra",
            "District": "Jalgaon",
            "Market": "Jamner(Neri)",
            "Commodity": "Maize",
            "Variety": "Yellow",
            "Grade": "FAQ",
            "Arrival_Date": "11/12/2006",
            "Min_Price": "640",
            "Max_Price": "660",
            "Modal_Price": "650",
            "Commodity_Code": "4"
        },
        {
            "State": "Maharashtra",
            "District": "Nashik",
            "Market": "Lasalgaon",
            "Commodity": "Bengal Gram(Gram)(Whole)",
            "Variety": "Kabul Small",
            "Grade": "FAQ",
            "Arrival_Date": "23/05/2006",
            "Min_Price": "3001",
            "Max_Price": "3001",
            "Modal_Price": "3001",
            "Commodity_Code": "6"
        },
        {
            "State": "Maharashtra",
            "District": "Ahmednagar",
            "Market": "Ahmednagar",
            "Commodity": "Bitter gourd",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "26/05/2006",
            "Min_Price": "1000",
            "Max_Price": "1200",
            "Modal_Price": "1100",
            "Commodity_Code": "81"
        },
        {
            "State": "Maharashtra",
            "District": "Mumbai",
            "Market": "Mumbai",
            "Commodity": "Cummin Seed(Jeera)",
            "Variety": "Cummin Seed(Jeera)",
            "Grade": "FAQ",
            "Arrival_Date": "14/01/2006",
            "Min_Price": "9000",
            "Max_Price": "12500",
            "Modal_Price": "10750",
            "Commodity_Code": "42"
        },
        {
            "State": "Maharashtra",
            "District": "Amarawati",
            "Market": "Achalpur",
            "Commodity": "Green Peas",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "27/07/2006",
            "Min_Price": "1300",
            "Max_Price": "1400",
            "Modal_Price": "1350",
            "Commodity_Code": "50"
        },
        {
            "State": "Maharashtra",
            "District": "Ahmednagar",
            "Market": "Pathardi",
            "Commodity": "Safflower",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "26/04/2006",
            "Min_Price": "1450",
            "Max_Price": "1450",
            "Modal_Price": "1450",
            "Commodity_Code": "59"
        },
        {
            "State": "Maharashtra",
            "District": "Ahmednagar",
            "Market": "Ahmednagar",
            "Commodity": "Guar",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "15/10/2006",
            "Min_Price": "1800",
            "Max_Price": "2000",
            "Modal_Price": "1900",
            "Commodity_Code": "75"
        },
        {
            "State": "Maharashtra",
            "District": "Raigad",
            "Market": "Panvel",
            "Commodity": "Bottle gourd",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "02/08/2006",
            "Min_Price": "1000",
            "Max_Price": "1300",
            "Modal_Price": "1200",
            "Commodity_Code": "82"
        },
        {
            "State": "Maharashtra",
            "District": "Buldhana",
            "Market": "Mehekar",
            "Commodity": "Arhar (Tur/Red Gram)(Whole)",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "06/03/2006",
            "Min_Price": "1450",
            "Max_Price": "1750",
            "Modal_Price": "1650",
            "Commodity_Code": "49"
        },
        {
            "State": "Maharashtra",
            "District": "Ahmednagar",
            "Market": "Ahmednagar",
            "Commodity": "Chikoos(Sapota)",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "02/01/2006",
            "Min_Price": "1000",
            "Max_Price": "1500",
            "Modal_Price": "1250",
            "Commodity_Code": "71"
        },
        {
            "State": "Maharashtra",
            "District": "Kolhapur",
            "Market": "Kolhapur",
            "Commodity": "Water Melon",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "20/09/2006",
            "Min_Price": "200",
            "Max_Price": "700",
            "Modal_Price": "450",
            "Commodity_Code": "73"
        },
        {
            "State": "Maharashtra",
            "District": "Pune",
            "Market": "Pune",
            "Commodity": "Chilly Capsicum",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "03/08/2006",
            "Min_Price": "1000",
            "Max_Price": "1500",
            "Modal_Price": "1250",
            "Commodity_Code": "88"
        },
        {
            "State": "Maharashtra",
            "District": "Nashik",
            "Market": "Nasik",
            "Commodity": "Tomato",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "22/06/2006",
            "Min_Price": "750",
            "Max_Price": "1500",
            "Modal_Price": "1125",
            "Commodity_Code": "78"
        },
        {
            "State": "Maharashtra",
            "District": "Yavatmal",
            "Market": "Aarni",
            "Commodity": "Jowar(Sorghum)",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "22/12/2006",
            "Min_Price": "620",
            "Max_Price": "639",
            "Modal_Price": "630",
            "Commodity_Code": "5"
        },
        {
            "State": "Maharashtra",
            "District": "Ahmednagar",
            "Market": "Ahmednagar",
            "Commodity": "Bhindi(Ladies Finger)",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "17/01/2006",
            "Min_Price": "1600",
            "Max_Price": "1700",
            "Modal_Price": "1650",
            "Commodity_Code": "85"
        },
        {
            "State": "Maharashtra",
            "District": "Bhandara",
            "Market": "Tumsar",
            "Commodity": "Other Pulses",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "04/03/2006",
            "Min_Price": "950",
            "Max_Price": "1127",
            "Modal_Price": "1050",
            "Commodity_Code": "97"
        },
        {
            "State": "Maharashtra",
            "District": "Beed",
            "Market": "Ambejaogai",
            "Commodity": "Niger Seed (Ramtil)",
            "Variety": "Niger Seed",
            "Grade": "FAQ",
            "Arrival_Date": "05/01/2006",
            "Min_Price": "1700",
            "Max_Price": "1700",
            "Modal_Price": "1700",
            "Commodity_Code": "98"
        },
        {
            "State": "Maharashtra",
            "District": "Jalgaon",
            "Market": "Bhusaval",
            "Commodity": "Green Gram (Moong)(Whole)",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "16/09/2006",
            "Min_Price": "2851",
            "Max_Price": "3100",
            "Modal_Price": "3000",
            "Commodity_Code": "9"
        },
        {
            "State": "Maharashtra",
            "District": "Ahmednagar",
            "Market": "Ahmednagar",
            "Commodity": "Corriander seed",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "06/01/2007",
            "Min_Price": "2900",
            "Max_Price": "2900",
            "Modal_Price": "2900",
            "Commodity_Code": "108"
        },
        {
            "State": "Maharashtra",
            "District": "Pune",
            "Market": "Pune",
            "Commodity": "Methi(Leaves)",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "11/10/2006",
            "Min_Price": "200",
            "Max_Price": "500",
            "Modal_Price": "350",
            "Commodity_Code": "46"
        },
        {
            "State": "Maharashtra",
            "District": "Amarawati",
            "Market": "Achalpur",
            "Commodity": "Lentil (Masur)(Whole)",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "31/05/2006",
            "Min_Price": "1650",
            "Max_Price": "1700",
            "Modal_Price": "1675",
            "Commodity_Code": "63"
        },
        {
            "State": "Maharashtra",
            "District": "Ahmednagar",
            "Market": "Shrirampur",
            "Commodity": "Linseed",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "17/10/2006",
            "Min_Price": "1801",
            "Max_Price": "1801",
            "Modal_Price": "1801",
            "Commodity_Code": "67"
        },
        {
            "State": "Maharashtra",
            "District": "Ahmednagar",
            "Market": "Shrirampur",
            "Commodity": "Methi Seeds",
            "Variety": "Methiseeds",
            "Grade": "FAQ",
            "Arrival_Date": "04/10/2006",
            "Min_Price": "1771",
            "Max_Price": "1771",
            "Modal_Price": "1771",
            "Commodity_Code": "47"
        },
        {
            "State": "Maharashtra",
            "District": "Kolhapur",
            "Market": "Kolhapur",
            "Commodity": "Sugar",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "04/01/2006",
            "Min_Price": "1860",
            "Max_Price": "1860",
            "Modal_Price": "1860",
            "Commodity_Code": "48"
        },
        {
            "State": "Maharashtra",
            "District": "Ahmednagar",
            "Market": "Ahmednagar",
            "Commodity": "Green Chilli",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "03/01/2006",
            "Min_Price": "600",
            "Max_Price": "700",
            "Modal_Price": "650",
            "Commodity_Code": "87"
        },
        {
            "State": "Maharashtra",
            "District": "Beed",
            "Market": "Ambejaogai",
            "Commodity": "Sesamum(Sesame,Gingelly,Til)",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "08/10/2007",
            "Min_Price": "3050",
            "Max_Price": "3150",
            "Modal_Price": "3094",
            "Commodity_Code": "11"
        },
        {
            "State": "Maharashtra",
            "District": "Ahmednagar",
            "Market": "Ahmednagar",
            "Commodity": "Cabbage",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "05/01/2007",
            "Min_Price": "300",
            "Max_Price": "400",
            "Modal_Price": "350",
            "Commodity_Code": "154"
        },
        {
            "State": "Maharashtra",
            "District": "Kolhapur",
            "Market": "Kolhapur",
            "Commodity": "Snakeguard",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "10/04/2007",
            "Min_Price": "1050",
            "Max_Price": "1050",
            "Modal_Price": "1050",
            "Commodity_Code": "156"
        },
        {
            "State": "Maharashtra",
            "District": "Ahmednagar",
            "Market": "Shrirampur",
            "Commodity": "Pomegranate",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "22/06/2007",
            "Min_Price": "200",
            "Max_Price": "225",
            "Modal_Price": "210",
            "Commodity_Code": "190"
        },
        {
            "State": "Maharashtra",
            "District": "Amarawati",
            "Market": "Varud",
            "Commodity": "Orange",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "22/02/2007",
            "Min_Price": "710",
            "Max_Price": "980",
            "Modal_Price": "850",
            "Commodity_Code": "18"
        },
        {
            "State": "Maharashtra",
            "District": "Ahmednagar",
            "Market": "Shrirampur",
            "Commodity": "Mustard",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "20/02/2007",
            "Min_Price": "1900",
            "Max_Price": "1900",
            "Modal_Price": "1900",
            "Commodity_Code": "12"
        },
        {
            "State": "Maharashtra",
            "District": "Mumbai",
            "Market": "Mumbai",
            "Commodity": "Arecanut(Betelnut/Supari)",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "22/03/2007",
            "Min_Price": "7000",
            "Max_Price": "12000",
            "Modal_Price": "9500",
            "Commodity_Code": "140"
        },
        {
            "State": "Maharashtra",
            "District": "Ahmednagar",
            "Market": "Rahuri",
            "Commodity": "Guava",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "25/12/2007",
            "Min_Price": "400",
            "Max_Price": "1000",
            "Modal_Price": "700",
            "Commodity_Code": "185"
        },
        {
            "State": "Maharashtra",
            "District": "Chandrapur",
            "Market": "Chandrapur",
            "Commodity": "Jamun(Narale Hannu)",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "05/06/2007",
            "Min_Price": "2000",
            "Max_Price": "2500",
            "Modal_Price": "2200",
            "Commodity_Code": "184"
        },
        {
            "State": "Maharashtra",
            "District": "Ahmednagar",
            "Market": "Ahmednagar",
            "Commodity": "Wheat",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "02/02/2007",
            "Min_Price": "1000",
            "Max_Price": "1300",
            "Modal_Price": "1275",
            "Commodity_Code": "1"
        },
        {
            "State": "Maharashtra",
            "District": "Ahmednagar",
            "Market": "Pathardi",
            "Commodity": "Castor Seed",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "25/07/2007",
            "Min_Price": "1400",
            "Max_Price": "1400",
            "Modal_Price": "1400",
            "Commodity_Code": "123"
        },
        {
            "State": "Maharashtra",
            "District": "Mumbai",
            "Market": "Mumbai",
            "Commodity": "Soanf",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "11/01/2007",
            "Min_Price": "8000",
            "Max_Price": "12000",
            "Modal_Price": "10000",
            "Commodity_Code": "135"
        },
        {
            "State": "Maharashtra",
            "District": "Nashik",
            "Market": "Nasik",
            "Commodity": "Lime",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "11/09/2007",
            "Min_Price": "300",
            "Max_Price": "400",
            "Modal_Price": "350",
            "Commodity_Code": "180"
        },
        {
            "State": "Maharashtra",
            "District": "Chandrapur",
            "Market": "Chandrapur",
            "Commodity": "Jack Fruit",
            "Variety": "Other",
            "Grade": "FAQ",
            "Arrival_Date": "19/05/2007",
            "Min_Price": "600",
            "Max_Price": "800",
            "Modal_Price": "700",
            "Commodity_Code": "182"
        }
    ]

module.exports = initialMarketData;